---
version: 2

build:
  os: ubuntu-24.04
  tools:
    # Keep in-sync with tox.ini/docs and ci.yml/docs
    python: "3.12"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
