language: python

# Test matrix
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Package installation
install:
  - pip install Pillow Wand
  - python setup.py install

# Run the tests
script:
  python runtests.py
