name: Publish to PyPI
on:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [released]

concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: false # Don't cancel in-progress publish jobs, they may be in the middle of uploading to PyPI!
env:
  PYTHONNOUSERSITE: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

permissions: {}

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/willow/
    permissions:
      contents: read # Needed to download release artifacts
      id-token: write # Needed for Trusted Publishing to PyPI
    steps:
      - name: Download release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          mkdir dist
          gh release download "$TAG" \
          --repo "$GITHUB_REPOSITORY" \
          --dir dist \
          --pattern "*.whl" \
          --pattern "*.tar.gz" \

      - name: Check provenance of release artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        # This answers the question: are the release artifacts we are about to
        # publish the same ones that were built and signed in the
        # build-release.yml workflow? Attack vector: someone might have modified
        # the draft release in between the build-release.yml workflow and this
        # publish.yml workflow, so we need to verify that the artifacts are what
        # we expect.
        run: |
          for file in dist/*.whl dist/*.tar.gz; do
            echo "Verifying $file"
            gh attestation verify "$file" \
              --repo $REPO \
              --signer-workflow github.com/$REPO/.github/workflows/build-release.yml
          done

      # All okay, now publish to PyPI!
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
